"""Added is_paid to Adjustments

Revision ID: 2e1ad89ccbb9
Revises: fedb1205e217
Create Date: 2026-02-27 11:36:01.951133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1ad89ccbb9'
down_revision: Union[str, Sequence[str], None] = 'fedb1205e217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adjustments', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adjustments', 'is_paid')
    # ### end Alembic commands ###
