"""Initial migration

Revision ID: 37bb13e756f9
Revises: 
Create Date: 2026-02-27 11:21:48.182055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bb13e756f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('threshold_min', sa.Float(), nullable=False),
    sa.Column('threshold_max', sa.Float(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('pending', 'employee', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('shift_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('acquiring', sa.Float(), nullable=False),
    sa.Column('salary_paid', sa.Float(), nullable=False),
    sa.Column('expense', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('birthdays', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('salary_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(sa.table('salary_settings',
        sa.column('level', sa.Integer),
        sa.column('threshold_min', sa.Float),
        sa.column('threshold_max', sa.Float),
        sa.column('base_salary', sa.Float),
        sa.column('percentage', sa.Float),
    ), [
        {'level': 1, 'threshold_min': 0,     'threshold_max': 15000,  'base_salary': 2500, 'percentage': 0.10},
        {'level': 2, 'threshold_min': 15000,  'threshold_max': 30000,  'base_salary': 0,    'percentage': 0.20},
        {'level': 3, 'threshold_min': 30000,  'threshold_max': None,   'base_salary': 0,    'percentage': 0.22},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('salary_settings')
    op.drop_table('plans')
    # ### end Alembic commands ###
